name: cinemania
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.6.0
  dio: ^5.4.1
  equatable: ^2.0.5
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^7.1.1
  flutter_glow: ^0.3.0
  flutter_hooks: ^0.20.5
  get_it: ^8.0.3
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.2
  internet_connection_checker: ^3.0.1
  intl: ^0.20.1
  like_button: ^2.0.5
  provider: ^6.1.2
  readmore: ^3.0.0
  rxdart: ^0.28.0
  scrollable_positioned_list: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.8
  injectable_generator: ^2.4.1
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.3.10
  mocktail: ^1.0.3
  bloc_test: ^9.1.6
  import_sorter: ^4.6.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  background_image: assets/splash.png

flutter:
  uses-material-design: true
  fonts:
    - family: MyIcons
      fonts:
      - asset: assets/MyIcons.ttf
  assets:
    - assets/
    - .env
